# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oCVX4dAcvi8Ke0Y-4Hs33CZbMqltVHa5
"""

list1=[1,2,3,4]
for i in list1:
  print(i**2 , end=" ")

